import matplotlib.pyplot as plt

params = {
    "font.family": "serif",
    "font.sans-serif": "Times New Roman",
    "font.size": 14,
    "lines.linewidth": 2,
    "text.usetex": False,
    "xtick.top": True,
    "xtick.minor.visible": True,
    "ytick.minor.visible": True,
    "xtick.direction": "in",
    "xtick.major.top": True,
    "xtick.major.bottom": True,
    "xtick.minor.top": True,
    "xtick.minor.bottom": True,
    "xtick.minor.width": 1,
    "xtick.major.width": 1,
    "xtick.minor.size": 3,
    "xtick.major.size": 6,
    "ytick.right": True,
    "ytick.direction": "in",
    "ytick.major.left": True,
    "ytick.major.right": True,
    "ytick.minor.left": True,
    "ytick.minor.right": True,
    "ytick.minor.width": 1,
    "ytick.major.width": 1,
    "ytick.minor.size": 3,
    "ytick.major.size": 6,
    "legend.frameon": False,
    "lines.markersize": 4.0,
    "axes.formatter.use_mathtext": True,
    "figure.figsize": (4.5, 4),
}

plt.rcParams.update(params)
